version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_NAME: "Laravel"
      APP_ENV: production
      APP_DEBUG: true
      APP_KEY: base64:fD3TNkGsIeTTfi3zENkY9YcF7TyXdxnSF5QBXIR2v3E=
      APP_URL: http://localhost:8000

      # Database
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: nmfashion_db
      DB_USERNAME: nmfashion_db_user
      DB_PASSWORD: PMevoLejY4YL3ZMrDTcZIecoEg9oebZc

      # Mail
      MAIL_MAILER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: mohibullahasib2004@gmail.com
      MAIL_PASSWORD: "ctsl peiv mdpo lyvu"
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: mohibullahasib2004@gmail.com
      MAIL_FROM_NAME: "NM Fashion"

      # Cache / Queue / Session
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120

    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nmfashion_db
      POSTGRES_USER: nmfashion_db_user
      POSTGRES_PASSWORD: PMevoLejY4YL3ZMrDTcZIecoEg9oebZc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
